import { IHistoricApi } from "@/interfaces/historic-api";

export function useApiController() {
  const dataTableApi: IHistoricApi[] = [
    {
      id: "1",
      ddd: "11",
      number: "11900000000",
      anatel: "valid",
      datePortate: new Date().toLocaleString("pt-BR", {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        second: undefined,
      }),
      municipality: "São Paulo",
      municipalityRegion: "São Paulo",
      operatorNow: "Claro aaaaaaaaaaaaaaaaaaaa",
      operatorOrigem: "Vivo aaaaaaaaaaaaaaaaaaaa",
      portate: true,
      type: "fixos",
      uf: "SP",
      origen: "https://google.com",
      dateAndHour: new Date().toLocaleString("pt-BR", {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        second: undefined,
      }),
    },
    {
      id: "2",
      ddd: "11",
      number: "11900000000",
      anatel: "valid",
      datePortate: new Date().toLocaleString("pt-BR", {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        second: undefined,
      }),
      municipality: "São Paulo",
      municipalityRegion: "São Paulo",
      operatorNow: "Claro aaaaaaaaaaaaaaaaaaaa",
      operatorOrigem: "Vivo aaaaaaaaaaaaaaaaaaaa",
      portate: true,
      type: "fixos",
      uf: "SP",
      origen: "https://google.com",
      dateAndHour: new Date().toLocaleString("pt-BR", {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        second: undefined,
      }),
    },
    {
      id: "3",
      ddd: "11",
      number: "11900000000",
      anatel: "valid",
      datePortate: new Date().toLocaleString("pt-BR", {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        second: undefined,
      }),
      municipality: "São Paulo",
      municipalityRegion: "São Paulo",
      operatorNow: "Claro aaaaaaaaaaaaaaaaaaaa",
      operatorOrigem: "Vivo aaaaaaaaaaaaaaaaaaaa",
      portate: true,
      type: "fixos",
      uf: "SP",
      origen: "https://google.com",
      dateAndHour: new Date().toLocaleString("pt-BR", {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        second: undefined,
      }),
    },
  ];

  return { dataTableApi };
}
